# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'visionalgmain.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import QSize, Qt
from PyQt5.QtGui import QIcon


class Ui_VisionAlgMain(object):
    def setupUi(self, VisionAlgMain):
        VisionAlgMain.setObjectName("VisionAlgMain")
        VisionAlgMain.resize(1280, 720)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(VisionAlgMain.sizePolicy().hasHeightForWidth())
        VisionAlgMain.setSizePolicy(sizePolicy)
        VisionAlgMain.setMinimumSize(QtCore.QSize(1280, 720))
        VisionAlgMain.setMaximumSize(QtCore.QSize(9999, 9999))
        VisionAlgMain.setStyleSheet("background-color: #EAEAEA;")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(VisionAlgMain)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.widget_menu = QtWidgets.QWidget(VisionAlgMain)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_menu.sizePolicy().hasHeightForWidth())
        self.widget_menu.setSizePolicy(sizePolicy)
        self.widget_menu.setMinimumSize(QtCore.QSize(64, 720))
        self.widget_menu.setMaximumSize(QtCore.QSize(64, 9999))
        self.widget_menu.setStyleSheet("background-color: #EAEAEA;color: #EAEAEA;")
        self.widget_menu.setObjectName("widget_menu")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget_menu)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(20, 30, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_2.addItem(spacerItem)

        # self.btnMenu_BgModel = QtWidgets.QToolButton(self.widget_menu)
        # self.btnMenu_BgModel.setStyleSheet("color: rgb(255, 255, 255);")
        # self.btnMenu_BgModel.setObjectName("btnMenu_BgModel")
        # self.btnMenu_BgModel.setIcon(QIcon("icons/model.png"))
        # self.btnMenu_BgModel.setIconSize(QSize(32, 32))
        # self.btnMenu_BgModel.setToolButtonStyle(Qt.ToolButtonTextUnderIcon)
        # self.btnMenu_BgModel.setText("背景建模")
        # self.btnMenu_BgModel.setFixedSize(64, 64)
        # self.verticalLayout_2.addWidget(self.btnMenu_BgModel)

        self.btnMenu_Detect = QtWidgets.QToolButton(self.widget_menu)
        self.btnMenu_Detect.setStyleSheet("color: rgb(255, 255, 255);")
        self.btnMenu_Detect.setObjectName("btnMenu_Detect")
        self.btnMenu_Detect.setIcon(QIcon("client/icons/persondetect.png"))
        self.btnMenu_Detect.setIconSize(QSize(32, 32))
        self.btnMenu_Detect.setToolButtonStyle(Qt.ToolButtonTextUnderIcon)
        self.btnMenu_Detect.setText("行人检测")
        self.btnMenu_Detect.setFixedSize(64, 64)
        self.verticalLayout_2.addWidget(self.btnMenu_Detect)

        self.btnMenu_Track = QtWidgets.QToolButton(self.widget_menu)
        self.btnMenu_Track.setStyleSheet("color: rgb(255, 255, 255);")
        self.btnMenu_Track.setObjectName("btnMenu_Track")
        self.btnMenu_Track.setIcon(QIcon("client/icons/track.png"))
        self.btnMenu_Track.setIconSize(QSize(32, 32))
        self.btnMenu_Track.setToolButtonStyle(Qt.ToolButtonTextUnderIcon)
        self.btnMenu_Track.setText("行人跟踪")
        self.btnMenu_Track.setFixedSize(64, 64)
        self.verticalLayout_2.addWidget(self.btnMenu_Track)

        self.btnMenu_PersonParse = QtWidgets.QToolButton(self.widget_menu)
        self.btnMenu_PersonParse.setObjectName("btnMenu_PersonParse")
        self.btnMenu_PersonParse.setStyleSheet("color: rgb(255, 255, 255);")
        self.btnMenu_PersonParse.setIcon(QIcon("client/icons/parser.png"))
        self.btnMenu_PersonParse.setIconSize(QSize(32, 32))
        self.btnMenu_PersonParse.setToolButtonStyle(Qt.ToolButtonTextUnderIcon)
        self.btnMenu_PersonParse.setText("行人解析")
        self.btnMenu_PersonParse.setFixedSize(64, 64)
        self.verticalLayout_2.addWidget(self.btnMenu_PersonParse)

        self.btnMenu_PersonSearch = QtWidgets.QToolButton(self.widget_menu)
        self.btnMenu_PersonSearch.setObjectName("btnMenu_PersonSearch")
        self.btnMenu_PersonSearch.setStyleSheet("color: rgb(255, 255, 255);")
        self.btnMenu_PersonSearch.setObjectName("btnMenu_PersonSearch")
        self.btnMenu_PersonSearch.setIcon(QIcon("client/icons/search.png"))
        self.btnMenu_PersonSearch.setIconSize(QSize(32, 32))
        self.btnMenu_PersonSearch.setToolButtonStyle(Qt.ToolButtonTextUnderIcon)
        self.btnMenu_PersonSearch.setText("行人检索")
        self.btnMenu_PersonSearch.setFixedSize(64, 64)
        self.verticalLayout_2.addWidget(self.btnMenu_PersonSearch)

        # self.btnMenu_ActorRecognition = QtWidgets.QToolButton(self.widget_menu)
        # self.btnMenu_ActorRecognition.setObjectName("btnMenu_ActorRecognition")
        # self.btnMenu_ActorRecognition.setStyleSheet("color: rgb(255, 255, 255);")
        # self.btnMenu_ActorRecognition.setIcon(QIcon("icons/actor.png"))
        # self.btnMenu_ActorRecognition.setIconSize(QSize(32, 32))
        # self.btnMenu_ActorRecognition.setToolButtonStyle(Qt.ToolButtonTextUnderIcon)
        # self.btnMenu_ActorRecognition.setText("行为识别")
        # self.btnMenu_ActorRecognition.setFixedSize(64, 64)
        # self.verticalLayout_2.addWidget(self.btnMenu_ActorRecognition)

        self.btnMenu_FaceDetect = QtWidgets.QToolButton(self.widget_menu)
        self.btnMenu_FaceDetect.setObjectName("btnMenu_FaceDetect")
        self.btnMenu_FaceDetect.setStyleSheet("color: rgb(255, 255, 255);")
        self.btnMenu_FaceDetect.setIcon(QIcon("client/icons/face_det.png"))
        self.btnMenu_FaceDetect.setIconSize(QSize(32, 32))
        self.btnMenu_FaceDetect.setToolButtonStyle(Qt.ToolButtonTextUnderIcon)
        self.btnMenu_FaceDetect.setText("人脸检测")
        self.btnMenu_FaceDetect.setFixedSize(64, 64)
        self.verticalLayout_2.addWidget(self.btnMenu_FaceDetect)

        self.btnMenu_FaceRecognition = QtWidgets.QToolButton(self.widget_menu)
        self.btnMenu_FaceRecognition.setObjectName("btnMenu_FaceRecognition")
        self.btnMenu_FaceRecognition.setStyleSheet("color: rgb(255, 255, 255);")
        self.btnMenu_FaceRecognition.setIcon(QIcon("client/icons/face_rec.png"))
        self.btnMenu_FaceRecognition.setIconSize(QSize(32, 32))
        self.btnMenu_FaceRecognition.setToolButtonStyle(Qt.ToolButtonTextUnderIcon)
        self.btnMenu_FaceRecognition.setText("人脸识别")
        self.btnMenu_FaceRecognition.setFixedSize(64, 64)
        self.verticalLayout_2.addWidget(self.btnMenu_FaceRecognition)



        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.horizontalLayout_2.addWidget(self.widget_menu)
        self.widget_show = QtWidgets.QWidget(VisionAlgMain)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_show.sizePolicy().hasHeightForWidth())
        self.widget_show.setSizePolicy(sizePolicy)
        self.widget_show.setMinimumSize(QtCore.QSize(1216, 720))
        self.widget_show.setMaximumSize(QtCore.QSize(9999, 9999))
        self.widget_show.setStyleSheet("background-color:#EAEAEA;")
        self.widget_show.setObjectName("widget_show")


        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget_show)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.widget_alg = QtWidgets.QWidget(self.widget_show)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_alg.sizePolicy().hasHeightForWidth())
        self.widget_alg.setSizePolicy(sizePolicy)
        self.widget_alg.setMinimumSize(QtCore.QSize(1216, 30))
        self.widget_alg.setMaximumSize(QtCore.QSize(9999, 30))
        self.widget_alg.setStyleSheet("background-color:#3C3C3C;color:white;")
        self.widget_alg.setObjectName("widget_alg")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget_alg)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(5)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.btn_login = QtWidgets.QPushButton(self.widget_alg)
        self.btn_login.setStyleSheet("color:white")
        self.btn_login.setObjectName("btn_login")
        self.horizontalLayout_3.addWidget(self.btn_login)
        self.btn_logout = QtWidgets.QPushButton(self.widget_alg)
        self.btn_logout.setStyleSheet("color:white")
        self.btn_logout.setObjectName("btn_logout")
        self.horizontalLayout_3.addWidget(self.btn_logout)
        self.btn_online = QtWidgets.QPushButton(self.widget_alg)
        self.btn_online.setStyleSheet("color:white")
        self.btn_online.setObjectName("btn_online")
        self.horizontalLayout_3.addWidget(self.btn_online)
        self.btn_offline = QtWidgets.QPushButton(self.widget_alg)
        self.btn_offline.setStyleSheet("color:white")
        self.btn_offline.setObjectName("btn_offline")
        self.horizontalLayout_3.addWidget(self.btn_offline)
        self.label_HCNetSDK = QtWidgets.QLabel(self.widget_alg)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_HCNetSDK.sizePolicy().hasHeightForWidth())
        self.label_HCNetSDK.setSizePolicy(sizePolicy)
        self.label_HCNetSDK.setStyleSheet("color:white;")
        self.label_HCNetSDK.setText("")
        self.label_HCNetSDK.setObjectName("label_HCNetSDK")
        self.horizontalLayout_3.addWidget(self.label_HCNetSDK)
        self.verticalLayout_3.addWidget(self.widget_alg)
        self.widget_main = QtWidgets.QWidget(self.widget_show)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_main.sizePolicy().hasHeightForWidth())
        self.widget_main.setSizePolicy(sizePolicy)
        self.widget_main.setMinimumSize(QtCore.QSize(1200, 640))
        self.widget_main.setMaximumSize(QtCore.QSize(9999, 9999))
        self.widget_main.setStyleSheet("font:9pt \"微软雅黑\";")
        self.widget_main.setObjectName("widget_main")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget_main)
        self.horizontalLayout.setContentsMargins(0, 0, 10, 10)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget_camera = QtWidgets.QWidget(self.widget_main)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_camera.sizePolicy().hasHeightForWidth())
        self.widget_camera.setSizePolicy(sizePolicy)
        self.widget_camera.setMinimumSize(QtCore.QSize(200, 600))
        self.widget_camera.setMaximumSize(QtCore.QSize(200, 700))
        self.widget_camera.setObjectName("widget_camera")
        self.labMessage = QtWidgets.QLabel(self.widget_camera)
        self.labMessage.setGeometry(QtCore.QRect(9, 653, 16, 18))
        self.labMessage.setText("")
        self.labMessage.setObjectName("labMessage")
        self.label = QtWidgets.QLabel(self.widget_camera)
        self.label.setGeometry(QtCore.QRect(20, 20, 168, 26))
        self.label.setStyleSheet("color:black")
        self.label.setObjectName("label")
        self.DVRsets_treeView = QtWidgets.QTreeWidget(self.widget_camera)
        self.DVRsets_treeView.setGeometry(QtCore.QRect(10, 50, 181, 621))
        self.DVRsets_treeView.setColumnCount(2)
        self.DVRsets_treeView.setObjectName("DVRsets_treeView")
        self.DVRsets_treeView.headerItem().setText(0, "1")
        self.DVRsets_treeView.headerItem().setText(1, "2")
        self.horizontalLayout.addWidget(self.widget_camera)
        self.gBoxMain = QtWidgets.QGroupBox(self.widget_main)
        self.gBoxMain.setMinimumSize(QtCore.QSize(960, 600))
        self.gBoxMain.setMaximumSize(QtCore.QSize(9999, 9999))
        self.gBoxMain.setStyleSheet("")
        self.gBoxMain.setTitle("")
        self.gBoxMain.setObjectName("gBoxMain")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.gBoxMain)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.lay1 = QtWidgets.QHBoxLayout()
        self.lay1.setSpacing(0)
        self.lay1.setObjectName("lay1")

        self.labVideo1 = QtWidgets.QLabel(self.gBoxMain)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labVideo1.sizePolicy().hasHeightForWidth())
        self.labVideo1.setSizePolicy(sizePolicy)
        self.labVideo1.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.labVideo1.setStyleSheet("color:black")
        self.labVideo1.setFrameShape(QtWidgets.QFrame.Panel)
        self.labVideo1.setText("")
        self.labVideo1.setAlignment(QtCore.Qt.AlignCenter)
        self.labVideo1.setObjectName("labVideo1")
        self.lay1.addWidget(self.labVideo1)

        self.labVideo2 = QtWidgets.QLabel(self.gBoxMain)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labVideo2.sizePolicy().hasHeightForWidth())
        self.labVideo2.setSizePolicy(sizePolicy)
        self.labVideo2.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.labVideo2.setStyleSheet("color:black")
        self.labVideo2.setFrameShape(QtWidgets.QFrame.Panel)
        self.labVideo2.setText("")
        self.labVideo2.setAlignment(QtCore.Qt.AlignCenter)
        self.labVideo2.setObjectName("labVideo2")
        self.lay1.addWidget(self.labVideo2)

        self.labVideo3 = QtWidgets.QLabel(self.gBoxMain)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labVideo3.sizePolicy().hasHeightForWidth())
        self.labVideo3.setSizePolicy(sizePolicy)
        self.labVideo3.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.labVideo3.setStyleSheet("color:black")
        self.labVideo3.setFrameShape(QtWidgets.QFrame.Panel)
        self.labVideo3.setText("")
        self.labVideo3.setAlignment(QtCore.Qt.AlignCenter)
        self.labVideo3.setObjectName("labVideo3")
        self.lay1.addWidget(self.labVideo3)

        self.labVideo4 = QtWidgets.QLabel(self.gBoxMain)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labVideo4.sizePolicy().hasHeightForWidth())
        self.labVideo4.setSizePolicy(sizePolicy)
        self.labVideo4.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.labVideo4.setStyleSheet("color:black")
        self.labVideo4.setFrameShape(QtWidgets.QFrame.Panel)
        self.labVideo4.setText("")
        self.labVideo4.setAlignment(QtCore.Qt.AlignCenter)
        self.labVideo4.setObjectName("labVideo4")
        self.lay1.addWidget(self.labVideo4)
        self.verticalLayout_4.addLayout(self.lay1)
        self.lay2 = QtWidgets.QHBoxLayout()
        self.lay2.setSpacing(0)
        self.lay2.setObjectName("lay2")
        self.labVideo5 = QtWidgets.QLabel(self.gBoxMain)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labVideo5.sizePolicy().hasHeightForWidth())
        self.labVideo5.setSizePolicy(sizePolicy)
        self.labVideo5.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.labVideo5.setStyleSheet("color:black")
        self.labVideo5.setFrameShape(QtWidgets.QFrame.Panel)
        self.labVideo5.setText("")
        self.labVideo5.setAlignment(QtCore.Qt.AlignCenter)
        self.labVideo5.setObjectName("labVideo5")
        self.lay2.addWidget(self.labVideo5)
        self.labVideo6 = QtWidgets.QLabel(self.gBoxMain)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labVideo6.sizePolicy().hasHeightForWidth())
        self.labVideo6.setSizePolicy(sizePolicy)
        self.labVideo6.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.labVideo6.setStyleSheet("color:black")
        self.labVideo6.setFrameShape(QtWidgets.QFrame.Panel)
        self.labVideo6.setText("")
        self.labVideo6.setAlignment(QtCore.Qt.AlignCenter)
        self.labVideo6.setObjectName("labVideo6")
        self.lay2.addWidget(self.labVideo6)
        self.labVideo7 = QtWidgets.QLabel(self.gBoxMain)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labVideo7.sizePolicy().hasHeightForWidth())
        self.labVideo7.setSizePolicy(sizePolicy)
        self.labVideo7.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.labVideo7.setStyleSheet("color:black")
        self.labVideo7.setFrameShape(QtWidgets.QFrame.Panel)
        self.labVideo7.setText("")
        self.labVideo7.setAlignment(QtCore.Qt.AlignCenter)
        self.labVideo7.setObjectName("labVideo7")
        self.lay2.addWidget(self.labVideo7)
        self.labVideo8 = QtWidgets.QLabel(self.gBoxMain)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labVideo8.sizePolicy().hasHeightForWidth())
        self.labVideo8.setSizePolicy(sizePolicy)
        self.labVideo8.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.labVideo8.setStyleSheet("color:black")
        self.labVideo8.setFrameShape(QtWidgets.QFrame.Panel)
        self.labVideo8.setText("")
        self.labVideo8.setAlignment(QtCore.Qt.AlignCenter)
        self.labVideo8.setObjectName("labVideo8")
        self.lay2.addWidget(self.labVideo8)
        self.verticalLayout_4.addLayout(self.lay2)
        self.lay3 = QtWidgets.QHBoxLayout()
        self.lay3.setSpacing(0)
        self.lay3.setObjectName("lay3")
        self.labVideo9 = QtWidgets.QLabel(self.gBoxMain)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labVideo9.sizePolicy().hasHeightForWidth())
        self.labVideo9.setSizePolicy(sizePolicy)
        self.labVideo9.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.labVideo9.setStyleSheet("color:black")
        self.labVideo9.setFrameShape(QtWidgets.QFrame.Panel)
        self.labVideo9.setText("")
        self.labVideo9.setAlignment(QtCore.Qt.AlignCenter)
        self.labVideo9.setObjectName("labVideo9")
        self.lay3.addWidget(self.labVideo9)
        self.labVideo10 = QtWidgets.QLabel(self.gBoxMain)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labVideo10.sizePolicy().hasHeightForWidth())
        self.labVideo10.setSizePolicy(sizePolicy)
        self.labVideo10.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.labVideo10.setStyleSheet("color:black")
        self.labVideo10.setFrameShape(QtWidgets.QFrame.Panel)
        self.labVideo10.setText("")
        self.labVideo10.setAlignment(QtCore.Qt.AlignCenter)
        self.labVideo10.setObjectName("labVideo10")
        self.lay3.addWidget(self.labVideo10)
        self.labVideo11 = QtWidgets.QLabel(self.gBoxMain)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labVideo11.sizePolicy().hasHeightForWidth())
        self.labVideo11.setSizePolicy(sizePolicy)
        self.labVideo11.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.labVideo11.setStyleSheet("color:black")
        self.labVideo11.setFrameShape(QtWidgets.QFrame.Panel)
        self.labVideo11.setText("")
        self.labVideo11.setAlignment(QtCore.Qt.AlignCenter)
        self.labVideo11.setObjectName("labVideo11")
        self.lay3.addWidget(self.labVideo11)
        self.labVideo12 = QtWidgets.QLabel(self.gBoxMain)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labVideo12.sizePolicy().hasHeightForWidth())
        self.labVideo12.setSizePolicy(sizePolicy)
        self.labVideo12.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.labVideo12.setStyleSheet("color:black")
        self.labVideo12.setFrameShape(QtWidgets.QFrame.Panel)
        self.labVideo12.setText("")
        self.labVideo12.setAlignment(QtCore.Qt.AlignCenter)
        self.labVideo12.setObjectName("labVideo12")
        self.lay3.addWidget(self.labVideo12)
        self.verticalLayout_4.addLayout(self.lay3)
        self.lay4 = QtWidgets.QHBoxLayout()
        self.lay4.setSpacing(0)
        self.lay4.setObjectName("lay4")
        self.labVideo13 = QtWidgets.QLabel(self.gBoxMain)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labVideo13.sizePolicy().hasHeightForWidth())
        self.labVideo13.setSizePolicy(sizePolicy)
        self.labVideo13.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.labVideo13.setStyleSheet("color:black")
        self.labVideo13.setFrameShape(QtWidgets.QFrame.Panel)
        self.labVideo13.setText("")
        self.labVideo13.setAlignment(QtCore.Qt.AlignCenter)
        self.labVideo13.setObjectName("labVideo13")
        self.lay4.addWidget(self.labVideo13)
        self.labVideo14 = QtWidgets.QLabel(self.gBoxMain)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labVideo14.sizePolicy().hasHeightForWidth())
        self.labVideo14.setSizePolicy(sizePolicy)
        self.labVideo14.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.labVideo14.setStyleSheet("color:black")
        self.labVideo14.setFrameShape(QtWidgets.QFrame.Panel)
        self.labVideo14.setText("")
        self.labVideo14.setAlignment(QtCore.Qt.AlignCenter)
        self.labVideo14.setObjectName("labVideo14")
        self.lay4.addWidget(self.labVideo14)
        self.labVideo15 = QtWidgets.QLabel(self.gBoxMain)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labVideo15.sizePolicy().hasHeightForWidth())
        self.labVideo15.setSizePolicy(sizePolicy)
        self.labVideo15.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.labVideo15.setStyleSheet("color:black")
        self.labVideo15.setFrameShape(QtWidgets.QFrame.Panel)
        self.labVideo15.setText("")
        self.labVideo15.setAlignment(QtCore.Qt.AlignCenter)
        self.labVideo15.setObjectName("labVideo15")
        self.lay4.addWidget(self.labVideo15)
        self.labVideo16 = QtWidgets.QLabel(self.gBoxMain)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labVideo16.sizePolicy().hasHeightForWidth())
        self.labVideo16.setSizePolicy(sizePolicy)
        self.labVideo16.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.labVideo16.setStyleSheet("color:black")
        self.labVideo16.setFrameShape(QtWidgets.QFrame.Panel)
        self.labVideo16.setText("")
        self.labVideo16.setAlignment(QtCore.Qt.AlignCenter)
        self.labVideo16.setObjectName("labVideo16")
        self.lay4.addWidget(self.labVideo16)
        self.verticalLayout_4.addLayout(self.lay4)
        self.horizontalLayout.addWidget(self.gBoxMain)
        self.verticalLayout_3.addWidget(self.widget_main)
        self.horizontalLayout_2.addWidget(self.widget_show)

        self.retranslateUi(VisionAlgMain)
        QtCore.QMetaObject.connectSlotsByName(VisionAlgMain)

    def retranslateUi(self, VisionAlgMain):
        _translate = QtCore.QCoreApplication.translate
        VisionAlgMain.setWindowTitle(_translate("VisionAlgMain", "视频结构化解析平台"))
        self.btn_login.setText(_translate("VisionAlgMain", "登录"))
        self.btn_logout.setText(_translate("VisionAlgMain", "注销"))
        self.btn_online.setText(_translate("VisionAlgMain", "在线处理"))
        self.btn_offline.setText(_translate("VisionAlgMain", "离线处理"))
        self.label.setText(_translate("VisionAlgMain", "在线摄像头（请点击登录按钮）"))


